name: Automate Hacker Newsletter

on:
  schedule:
    # Runs at 10:00 AM UTC every Friday
    - cron: '0 10 * * 5'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  blast:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Fire Newsletter Blast
        run: npm run newsletter
